[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 4_294_967_295
dynamic_test_linking = true
via_ir = true
solc = "0.8.30"
verbosity = 2
ffi = true
fs_permissions = [
  { access = "read-write", path = ".forge-snapshots"},
  { access = "read", path = "script/" }
]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
  "permit2/=lib/the-compact/lib/permit2/",
  "solady/=lib/solady/src/",
  "the-compact/=lib/the-compact/src/"
]

additional_compiler_profiles = [
  { name = "test", via_ir = false, optimizer = false }
]

compilation_restrictions = [
  { paths = "test/**", via_ir = false, optimizer = false }
]

[profile.default.fuzz]
runs = 10000

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100

[fmt]
line_length = 120
tab_width = 4
quote_style = "single"
sort_imports = true
number_underscore = "thousands"
